server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/easypsi
  http-port: 8080
  http-port-inner: 9001
  port: 443
  ssl:
    enabled: true
    key-store: "file:./config/server.jks"
    key-store-password: easypsi
    key-alias: easypsi-server
    key-password: easypsi
    key-store-type: JKS

spring:
  task:
    scheduling:
      pool:
        size: 10
  application:
    name: easypsi
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    hibernate.dialect: org.hibernate.dialect.SQLiteDialect
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./db/easypsi.sqlite
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 1
      connection-timeout: 5000
  jackson:
    deserialization:
      fail-on-missing-external-type-id-property: false
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
  web:
    locale: zh_CN # default locale, overridden by request "Accept-Language" header.

logging:
  level:
    root: info
    org:
      hibernate:
        type: debug

kusciaapi:
  address: root-kuscia-master:8083
  protocol: ${KUSCIA_PROTOCOL:mtls} # notls tls mtls
  tls:
    cert-file: config/certs/client.crt
    key-file: config/certs/client.pem
    ca-file: config/certs/ca.crt
  token-file: config/certs/token

job:
  max-parallelism: 1

easypsi:
  platform-type: CENTER
  node-id: kuscia-system
  center-platform-service: easypsi.master.svc
  gateway: http://localhost:8090
  auth:
    enabled: true
  response:
    extra-headers:
      Content-Security-Policy: "base-uri 'self';frame-src 'self';worker-src blob: 'self' data:;object-src 'self';"
  upload-file:
    max-file-size: -1    # -1 means not limit, e.g.  200MB, 1GB
    max-request-size: -1 # -1 means not limit, e.g.  200MB, 1GB
  data:
    host-path: /home/kuscia/p2p/
    dir-path: /app/data/
  version:
    easypsi: easypsiTag
    kuscia: kusciaTag
    secretflow: secretflowTag

tee:
  capsule-mana: capsule-manager.#.svc # tee capsule-manager service

springdoc:
  api-docs:
    enabled: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,readiness

inner-port:
  path:
    - /api/v1alpha1/project/edge/job/list
    - /api/v1alpha1/project/job/create/kuscia
    - /api/v1alpha1/project/job/stop/kuscia
    - /api/v1alpha1/project/job/pause/kuscia
    - /api/v1alpha1/project/job/continue/kuscia
    - /api/v1alpha1/data/count/kuscia
