server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/easypsi
  http-port: 8080
  port: 443
  ssl:
    enabled: true
    key-store: "file:./config/server.jks"
    key-store-password: easypsi
    key-alias: easypsi-server
    key-password: easypsi
    key-store-type: JKS

spring:
  task:
    scheduling:
      pool:
        size: 10
  application:
    name: easypsi
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    hibernate.dialect: org.hibernate.dialect.SQLiteDialect
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./db/easypsi.sqlite
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 1
      connection-timeout: 5000
  jackson:
    deserialization:
      fail-on-missing-external-type-id-property: false
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
  web:
    locale: zh_CN # default locale, overridden by request "Accept-Language" header.

logging:
  level:
    root: info
    org:
      hibernate:
        type: info
  path: /app/log/easypsi

kusciaapi:
  address: ${KUSCIA_API_ADDRESS}
  tls:
    cert-file: config/certs/client.crt
    key-file: config/certs/client.pem
    ca-file: config/certs/ca.crt
  token-file: config/certs/token

fabric:
  is-open: false
  address:
  msp-id:
  channel-name:
  chain-code-name:
  override-auth:
  owner:
  sign-cert-path: config/fabric/signCert.pem
  keystore-path: config/fabric/keystore.pem
  tls-cert-path: config/fabric/tls.pem

job:
  max-parallelism: 1

easypsi:
  platform-type: P2P
  node-id: ${NODE_ID}
  center-platform-service: easypsi.master.svc
  p2p-platform-service: easypsi
  gateway: ${KUSCIA_GW_ADDRESS}
  auth:
    enabled: true
  response:
    extra-headers:
      Content-Security-Policy: "base-uri 'self';frame-src 'self';worker-src blob: 'self' data:;object-src 'self';"
  upload-file:
    max-file-size: -1    # -1 means not limit, e.g.  200MB, 1GB
    max-request-size: -1 # -1 means not limit, e.g.  200MB, 1GB
  data:
    host-path: ${HOST_PATH}
    dir-path: /app/data/
  job:
    audit: true
  version:
    easypsi-image: ${EASYPSI_IMAGE}
    kuscia-image: ${KUSCIA_IMAGE}
    secretflow-image: ${SECRETFLOW_IMAGE}

